### ISSUE TITLE
payloadLength specification

### ISSUE THREAD

**Issue by bruno-f-cruz** [harp-tech/reflex-generator#8]
https://github.com/harp-tech/reflex-generator/blob/9f055d286303284695668246d44eb5eb6249a184/schema/device.json#L130

@glopesdev 
Should this not allow the user to enter, in addition to an `int`, a `str` or `str[]`? I thought this is what we were using to keep track of labels of the data?

**Comment by glopesdev** [comment]
@bruno-f-cruz the string functionality has now been moved into the `payloadSpec` field. I am uploading the example metadata with a case for this to demonstrate.
